CREATE TABLE IF NOT EXISTS users (
  user_id       INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_name     VARCHAR(40)     NOT NULL,
  email         VARCHAR(254)     NOT NULL,
  password      VARCHAR(20)     NOT NULL,
  introduce		VARCHAR(100)	NOT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oshis (
  oshi_name		VARCHAR(100) NOT NULL,
  oshi_id		INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT
  tag			VARCHAR(100) NOT NULL,
  birthdate		DATE NOT NULL DEFAULT,
  oshi_meet		VARCHAR(1024)
  like_point	VARCHAR(254)
  free_space	VARCHAR(1024)
  interest		VARCHAR(1024)
  created_at	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS comments (
  nice_num		INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  oshi_id    INTEGER UNSIGNED NOT NULL,
  comment       VARCHAR(255)     NOT NULL DEFAULT '',
  user_id       INTEGER UNSIGNED NOT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
